export enum ActionType {
  SET_NAME = "setName",
  SET_SPECIES = "setSpecies",
  SET_SEX = "setSex",
  SET_BREEDS = "setBreeds",
  SET_BREED = "setBreed",
  ADD_BREED = "addBreed",
  REMOVE_BREED = "removeBreed",
  CLEAR_BREEDS = "clearBreeds",
  SET_BREED_TYPE = "setBreedType",
  SET_AGE = "setAge",
  SET_WEIGHT = "setWeight",
  SET_MICROCHIP = "setMicrochip",
  SET_DESCRIPTION = "setDescription",
  ADD_COAT_COLOR = "addCoatColor",
  REMOVE_COAT_COLOR = "removeCoatColor",
  CLEAR_COAT_COLORS = "clearCoatColors",
  ADD_EYE_COLOR = "addEyeColor",
  REMOVE_EYE_COLOR = "removeEyeColor",
  CLEAR_EYE_COLORS = "clearEyeColors",
  SET_UPLOADED_IMAGE = "setUploadedImage",
  REMOVE_SAVED_IMAGE = "removeSavedImage",
  ADD_SAVED_IMAGE = "addSavedImage",
  SET_STATUS = "setStatus",
}
